### ISSUE TITLE
Add "forking this guide" or "using this guide outside 18F".

### ISSUE THREAD

**Issue by adunkman** [18F/eng-hiring#129]
We have a few resources that we could share with other groups within TTS who are interested in hiring in a similar way to 18F Engineering beyond just the questions and templates linked in the interview guides, it’d be cool to share that somewhere on the site.

**Comment by adunkman** [comment]
I’m thinking of the [Interview Question Bank](https://docs.google.com/document/d/1oYmx_93-mq2QrqICCo8SNk8hHmnPPonPA1kg0vhy540/edit#heading=h.p3zgydisjuv3) mainly… but I’d bet we have more things laying around to share.

**Comment by lauraGgit** [comment]
closed by #133
