### ISSUE TITLE
Use templates with a copy button for interview guides?

### ISSUE THREAD

**Issue by adunkman** [18F/eng-hiring#130]
Our [phone screen guide uses a "Make a copy" button](https://eng-hiring.18f.gov/phone-screens/#before-the-call) but our interview guides don’t follow the same pattern.

**Comment by adunkman** [comment]
I’m actually not 100% sure if that is something we should be doing for interview guides… the TTS Talent Team usually creates notes docs for interviews, I wouldn’t want to interfere with their process and create a bunch of duplicated and randomly-permissioned documents… 🤔

**Comment by lauraGgit** [comment]
for the technical interview - partially closed by #127

**Comment by lauraGgit** [comment]
and fully closed by #132
