### ISSUE TITLE
Link to interview training deck doesn't work

### ISSUE THREAD

**Issue by alexsobledotgov** [18F/eng-hiring#146]
(At least for me!)

Fix the permissions in Drive and/or update the link.

https://docs.google.com/presentation/d/1uezTFgDgNFvRlegkFnXDcHDS_wD6gsBsICFbbZJc-mE/edit

**Comment by ccostino** [comment]
This might have been superseded by the training Talent does as well now as it is.  We could follow up with them to see if there's a newer slide deck to use!

**Comment by alexsobledotgov** [comment]
@ccostino Agreed, breaking that out into a follow-on issue
