### ISSUE TITLE
Add automation to add opened issues to Delivery Assurance board

### ISSUE THREAD

**Issue by Sgtpluck** [18F/eng-hiring#148]
**Point of contact on this issue**
@Sgtpluck 

**Billable?**
- [x] Yes
If yes, tock code:
1813

**Skills needed**
- [x] Engineering

**Timeline**
Does this need to happen in the next two weeks?
- [x] Yes

How much time do you anticipate this work taking?
1/2 day

### A description of the work
In order to get the Delivery Assurance shared board working automatically, we need to add a GitHub action to the eng-hiring repo.

Example Action here:
https://github.com/18F/18f.gsa.gov/blob/main/.github/workflows/on_new_issue.yml

This requires adding the on_new_issue secrets to the repo, which are:
DELIVERY_ASSURANCE_PROJECT_APP_ID
DELIVERY_ASSURANCE_PROJECT_INSTALLATION_ID
DELIVERY_ASSURANCE_PROJECT_PRIVATE_KEY

### Acceptance Criteria

As an 18F staff member who opens an issue with the $TBD label on the eng-hiring repo, I can immediately see that issue in the Delivery Assurance [shared Projects board](https://github.com/orgs/18F/projects/41/views/1?query=is%3Aopen+sort%3Aupdated-desc).

This ticket is part of [#9 ](https://github.com/18F/delivery-assurance/issues/9)

### Other context:

@alexsoble mentioned the desire to have only issues with specific labels flow to the shared board -- that works for the DA team! Let's discuss in the comments what labels would work best for y'all.

**Comment by alexsobledotgov** [comment]
@Sgtpluck  Let's use a `da-team` label to send issues to the shared board! Just made one: https://github.com/18F/eng-hiring/labels/da-team
