### ISSUE TITLE
Add the 18F Delivery Assurance team as an admin

### ISSUE THREAD

**Issue by mgwalker** [18F/eng-hiring#150]
The [18F Delivery Assurance team](https://github.com/orgs/18F/teams/18f-delivery-assurance/members) should be given permissions on this repo. Admin permissions are preferable to reduce friction for the DA team going forward, but this repo's owners have discretion.

**Comment by alexsobledotgov** [comment]
👋 @mgwalker, let me sync with @ccostino on this one when he's back in the office & then we'll get back to you.

I love the use of a GitHub Team here to simplify permissions and make onboarding frictionless. When it comes to granting admin permissions, I think it's worth considering the least privilege security principle as a reason to limit admin permissions to a smaller group.

I'm assuming that we can grant the DA team write permissions without granting admin permissions. 

I also don't anticipate that the eng-hiring site will be as much as a focus of effort for the DA team as, say, the 18F website or our discipline Guides & Methods.

**Comment by kfoley-18F** [comment]
It sounds like there is a conversation around how to best manage admin permissions for DA team needs. 
DA team is just 18F staff, and those folks are already maintaining 18F sites including this one. 
There absolutely WILL be things that DA team will be doing with a number of 18F repos, including this one. 

I'm curious why there is resistance to this request?

**Comment by mgwalker** [comment]
@alexsoble Any update?

**Comment by alexsobledotgov** [comment]
@mgwalker I gave DA team Write access to the repository, same decision as the Tock repo owners made: https://github.com/18F/tock/issues/1562.

@kfoley-18F Resistance to the admin permissions specifically is coming from least privilege principle. I don't anticipate that DA team will need to be changing secrets or updating other admin settings for eng-hiring on a regular basis, so I'd like to defer to the least privilege security principle in this scenario.

I'll close this out for now but I am happy to revisit this in the future. We may find that the DA team has a need to make admin changes on a regular basis, or repo owners may lose discretion over this choice. Very easy to update/revise permissions. cc @ccostino
