### ISSUE TITLE
More clearly break out the content that's relevant to candidates

### ISSUE THREAD

**Issue by jacobian** [18F/eng-hiring#17]
Right now the site serves 2 purposes: for candidates and for interviewers. This means that as a candidate there's a lot of content to wade through that's entirely not relevant. We should have a more clear landing/ToC for candidates to find the interesting relevant stuff.

**Comment by adunkman** [comment]
This is slightly outdated at this point, but the [candidate-specific part](https://eng-hiring.18f.gov/pre-work/) is now pulled out on its own, and candidates continually comment that they enjoy reading the details of the process during phone screens. Will close as complete. :high-five:
