### ISSUE TITLE
Consider additional question "how do you deal with organizational change"?

### ISSUE THREAD

**Issue by ctro** [18F/eng-hiring#40]
For future interview consideration: After looking through the core values questions, I realized there's nothing about how the candidate deals with organizational change, which seems like a potentially valuable thing to ask about.

(cc @hbillings)

**Comment by ctro** [comment]
Product chapter asks a number of questions that are basically

> So everything is going fine and then the rug gets pulled out from under you, what do?

**Comment by ctro** [comment]
Maybe direct is best

> Tell me about a time you experienced organizational change.  How did you approach the change? How did it affect you?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
