### ISSUE TITLE
Be consistent with time expectations

### ISSUE THREAD

**Issue by ctro** [18F/eng-hiring#42]
https://eng-hiring.18f.gov/pre-work/

Pre work page says the interview will take ~30 mins.
We schedule 60 mins.

**Comment by adborden** [comment]
I definitely use the 60 minutes. If the code is a bit weak, you need the time to pull out the information through dialog to be convinced the candidate knows their stuff.

**Comment by ertzeid** [comment]
I think it would make the most sense to just clear up the expectations with something like:

> We expect this to take 30 minutes, but schedule 60 to allow time for extra discussion, and for the candidate to ask questions of the interviewer.

I would be concerned that 30 minutes would make the interviews feel really rushed and stressful for everyone. But having some suggested language for the interviewer like "we don't have to take the full time, and it's not necessarily a bad sign if we don't, but we want to make sure we don't feel rushed, either" or something.
