### ISSUE TITLE
Brainstorm new homeworks

### ISSUE THREAD

**Issue by ctro** [18F/eng-hiring#53]
Adhoc / Homeworks don’t seem like they’re working super well
Look around, find some fresh homeworks somewhere other than AdHoc?
Invent our own?

**Comment by ctro** [comment]
Useful assignments will be close to the actual work we're doing.
@alexsoble, I'm wondering if you have any ideas here. I'll continue to think.

**Comment by ctro** [comment]
AdHoc keeps iterating their homeworks, which is good for us. https://homework.adhoc.team/assignments/
I'm having a hard time finding anything that would work better.
Perhaps we mitigate by making the "bring your own" option more obvious.

**Comment by ctro** [comment]
Current guidance: https://eng-hiring.18f.gov/pre-work/#instructions-to-candidates

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
