### ISSUE TITLE
Update templates to be inline with 18F Websites Modernization Plan

### ISSUE THREAD

**Issue by adunkman** [18F/eng-hiring#91]
The footer needs to be updated to include the GSA logo at very least — with the goal of bringing it closer in design to https://ux-guide.18f.gov/.

There are a few upstream templates here, and it’s unclear which is the way forward (but we shouldn’t be implementing another):

- https://github.com/18F/uswds-jekyll
- https://github.com/18F/federalist-jekyll-uswds-18f-port
- https://github.com/18F/isildurs-bane

**Comment by adunkman** [comment]
Requested to be completed before the end of calendar 2020.

**Comment by lauraGgit** [comment]
closed by #95
